Support update of silences
giantswarm/silence-operator pull request #200
Opened 2022-06-01 10:21 UTC by QuentinBisson

Allow update of silences if they are updated in the silence repo

## Checklist

- [x] Update changelog in CHANGELOG.md.

2022-06-01 11:28 UTC, TheoBrigitte requested changes

2022-06-01 11:28 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			silence := filteredSilences[i]
Just use the already existing `silence` variable.

2022-06-01 11:28 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			err = ctrlClient.Get(ctx, objectKey, &existingSilence)
There is no need to fetch the current silence again, it was already fetched at the beginning of this function. Or do you think this is error prone? If yes why and comment please.

2022-06-01 12:20 UTC, QuentinBisson commented on cmd/sync/runner.go
> +			err = ctrlClient.Get(ctx, objectKey, &existingSilence)
No you are right here :)
There can be race conditions but this will be fixed 5 minutes later anyway

2022-06-01 12:20 UTC, QuentinBisson commented on cmd/sync/runner.go
> +			silence := filteredSilences[i]
The old code kinda shadowed this variable. Thanks

2022-06-01 17:25 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			err = ctrlClient.Get(ctx, objectKey, &existingSilence)
Nothing changes silences beside this job anyway.

2022-06-01 17:31 UTC, TheoBrigitte requested changes
Good overall, just few remarks.

2022-06-01 17:31 UTC, TheoBrigitte commented on cmd/sync/runner.go
>  		if !silenceInList(silence, currentSilences.Items) {
Nitpicking but feels more readable to me.

```suggestion
		if !silenceInList(silence, currentSilences.Items) {
			// create desired silences
```

2022-06-01 17:31 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			r.logger.LogCtx(ctx, "level", "debug", "message", fmt.Sprintf("updating desired silence CR %#q", silence.Name))
Nitpick to make things more readable

```suggestion
		} else {
			// update desired silences
			r.logger.LogCtx(ctx, "level", "debug", "message", fmt.Sprintf("updating desired silence CR %#q", silence.Name))
```

2022-06-01 17:31 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			err = ctrlClient.Update(ctx, &filteredSilences[i])
Using the `silence` is less confusing.

```suggestion
			updateMeta(existingSilence, &silence)
			err = ctrlClient.Update(ctx, &silence)
```

2022-06-02 08:07 UTC, QuentinBisson commented on cmd/sync/runner.go
> +			err = ctrlClient.Update(ctx, &filteredSilences[i])
I had to use this to avoid the `Implicit memory aliasing in for loop` error thrown by the go compiler

2022-06-02 14:31 UTC, TheoBrigitte approved these changes

2022-06-02 14:31 UTC, TheoBrigitte commented on cmd/sync/runner.go
> +			err = ctrlClient.Update(ctx, &filteredSilences[i])
Ok fine.

2022-06-02 14:32 UTC, merged

2022-06-03 08:08 UTC, QuentinBisson commented
towards https://github.com/giantswarm/giantswarm/issues/22219