Point silence operator to mimir
giantswarm/silence-operator pull request #318
Opened 2023-06-22 10:56 UTC by QuentinBisson

## Checklist

- [x] Update changelog in CHANGELOG.md.

2023-06-22 11:23 UTC, QuentinBisson commented
![image](https://github.com/giantswarm/silence-operator/assets/2787548/954ed4ca-b42d-406d-ac34-a86b6f19f565)

2024-06-27 09:30 UTC, TheoBrigitte requested changes

2024-06-27 09:30 UTC, TheoBrigitte commented on helm/silence-operator/templates/configmap.yaml
> +        tenantId: anonymous
This value should be configurable via values

2024-06-27 09:30 UTC, TheoBrigitte commented on helm/silence-operator/values.yaml
> +alertmanagerAddress: http://mimir-gateway.mimir.svc:8080/alertmanager
Let's not make this a default here, but instead use a placeholder

2024-06-27 09:30 UTC, TheoBrigitte commented on main.go
> +	daemonCommand.PersistentFlags().String(f.Service.AlertManager.TenantId, "anonymous", "Mimir alertmanager tenant id.")
This flag should have an empty string as default value.

2024-06-27 09:30 UTC, TheoBrigitte commented on pkg/alertmanager/mimirclient.go
> +	c        http.Client
http.Client should rather be embedded in httpClient in order to avoid obfuscation of the client capabilities.
This would also prevent redefining all the client method done below.

2024-06-27 11:45 UTC, QuentinBisson commented on main.go
> +	daemonCommand.PersistentFlags().String(f.Service.AlertManager.TenantId, "anonymous", "Mimir alertmanager tenant id.")
```suggestion
	daemonCommand.PersistentFlags().String(f.Service.AlertManager.TenantId, "", "Mimir alertmanager tenant id.")
```

2024-10-28 15:21 UTC, QuentinBisson commented on pkg/alertmanager/mimirclient.go
> +	c        http.Client
Sure that would be best but there's no way to call the do function of the http.client thought right?

2024-10-28 15:35 UTC, QuentinBisson commented on main.go
> +	daemonCommand.PersistentFlags().String(f.Service.AlertManager.TenantId, "", "Mimir alertmanager tenant id.")
```suggestion
	daemonCommand.PersistentFlags().String(f.Service.AlertManager.TenantId, "", "Alertmanager tenant id.")
```

2024-10-28 15:36 UTC, QuentinBisson commented on pkg/alertmanager/transport.go
> +		req.Header.Add("X-Scope-OrgID", t.tenantId)
We use a transport to avoid overrding functions of the http client

2024-11-04 15:06 UTC, QuentinBisson commented
@TheoBrigitte what do you think?

2024-11-05 11:39 UTC, TheoBrigitte approved these changes

2024-11-05 12:13 UTC, merged